export const mockChartData = [
    { name: 'Jan', sent: 0, received: 0 },
    { name: 'Feb', sent: 0, received: 0 },
    { name: 'Mar', sent: 0, received: 0 },
    { name: 'Apr', sent: 0, received: 0 },
    { name: 'May', sent: 0, received: 0 },
    { name: 'Jun', sent: 0, received: 0 },
    { name: 'Jul', sent: 0, received: 0 },
    { name: 'Aug', sent: 0, received: 0 },
    { name: 'Sep', sent: 0, received: 0 },
    { name: 'Oct', sent: 0, received: 0 },
    { name: 'Nov', sent: 0, received: 0 },
    { name: 'Dec', sent: 0, received: 0 },
];

export const balancechart31 = [{name: "1",amount: 0},
    {name: "2",amount: 0},
    {name: "3",amount: 0},
    {name: "4",amount: 0},
    {name: "5",amount: 0},
    {name: "6",amount: 0},
    {name: "7",amount: 0},
    {name: "8",amount: 0},
    {name: "9",amount: 0},
    {name: "10",amount: 0},
    {name: "11",amount: 0},
    {name: "12",amount: 0},
    {name: "13",amount: 0},
    {name: "14",amount: 0},
    {name: "15",amount: 0},
    {name: "16",amount: 0},
    {name: "17",amount: 0},
    {name: "18",amount: 0},
    {name: "19",amount: 0},
    {name: "20",amount: 0},
    {name: "21",amount: 0},
    {name: "22",amount: 0},
    {name: "23",amount: 0},
    {name: "24",amount: 0},
    {name: "25",amount: 0},
    {name: "26",amount: 0},
    {name: "27",amount: 0},
    {name: "28",amount: 0},
    {name: "29",amount: 0},
    {name: "30",amount: 0},
    {name: "31",amount: 0},
]

export const balancechart30 = balancechart31.slice(0, 30);
export const balancechart28 = balancechart31.slice(0, 28);
export const balancechart29 = balancechart31.slice(0, 29);
export const balancechartmonthly = [{name: "Jan",amount: 0},
    {name: "Feb",amount: 0},
    {name: "Mar",amount: 0},
    {name: "Apr",amount: 0},
    {name: "May",amount: 0},
    {name: "Jun",amount: 0},
    {name: "Jul",amount: 0},
    {name: "Aug",amount: 0},
    {name: "Sep",amount: 0},
    {name: "Oct",amount: 0},
    {name: "Nov",amount: 0},
    {name: "Dec",amount: 0},
]
export const dailyChartData31 = [
    { name: '1', sent: 0, received: 0 },
    { name: '2', sent: 0, received: 0 },
    { name: '3', sent: 0, received: 0 },
    { name: '4', sent: 0, received: 0 },
    { name: '5', sent: 0, received: 0 },
    { name: '6', sent: 0, received: 0 },
    { name: '7', sent: 0, received: 0 },
    { name: '8', sent: 0, received: 0 },
    { name: '9', sent: 0, received: 0 },
    { name: '10', sent: 0, received: 0 },
    { name: '11', sent: 0, received: 0 },
    { name: '12', sent: 0, received: 0 },
    { name: '13', sent: 0, received: 0 },
    { name: '14', sent: 0, received: 0 },
    { name: '15', sent: 0, received: 0 },
    { name: '16', sent: 0, received: 0 },
    { name: '17', sent: 0, received: 0 },
    { name: '18', sent: 0, received: 0 },
    { name: '19', sent: 0, received: 0 },
    { name: '20', sent: 0, received: 0 },
    { name: '21', sent: 0, received: 0 },
    { name: '22', sent: 0, received: 0 },
    { name: '23', sent: 0, received: 0 },
    { name: '24', sent: 0, received: 0 },
    { name: '25', sent: 0, received: 0 },
    { name: '26', sent: 0, received: 0 },
    { name: '27', sent: 0, received: 0 },
    { name: '28', sent: 0, received: 0 },
    { name: '29', sent: 0, received: 0 },
    { name: '30', sent: 0, received: 0 },
    { name: '31', sent: 0, received: 0 },
];

export const dailtchartData30 = dailyChartData31.slice(0, 30);
export const dailtchartData28 = dailyChartData31.slice(0, 28);
export const dailtchartData29 = dailyChartData31.slice(0, 29);