name: on build PR

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: gnerate prisma client
        run: cd packages/prisma && npm run generate --no-engine && cd ../..
      - name: Run Build
        run: npm run build
        